# Generated by Django 4.1.7 on 2023-03-24 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Ph_No',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Resume',
        ),
    ]
